services:
  minio:
    image: cgr.dev/chainguard/minio
    restart: always
    entrypoint: sh
    command: -c 'mkdir -p /data/langfuse && minio server --address ":9000" --console-address ":9001" /data'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 1s

  langfuse-worker:
    image: langfuse/langfuse-worker:3
    restart: always
    depends_on:
      minio:
        condition: service_healthy
    ports:
      - "127.0.0.1:3030:3030"
    env_file: .env

  langfuse-web:
    image: langfuse/langfuse:3
    restart: always
    depends_on:
      minio:
        condition: service_healthy
    ports:
      - "0.0.0.0:3000:3000"
    env_file: .env

volumes:
  minio_data:
    driver: local
